[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
    "pip install uv",
    "uv pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "mkdir -p cache/gather",
    "mkdir -p output"
]

[start]
cmd = "uv run uvicorn main:app --host 0.0.0.0 --port $PORT"