[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "uv"]

[phases.install]
cmds = [
    "uv venv /opt/venv",
    "uv pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "mkdir -p cache/gather",
    "mkdir -p output"
]

[start]
cmd = "/opt/venv/bin/python -m uvicorn main:app --host 0.0.0.0 --port $PORT"